name: Deployment CI/CD

on:
  push:
    branches: [ "deployment" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - name: Adding Environment Variables
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: connecting to ec2 and deploy the application
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker run -d -p 80:80 996648427470.dkr.ecr.ap-south-1.amazonaws.com/farm_chatapp:latest
      
